### ISSUE TITLE
目前XUEXUE_JSON_OBJECT_MX只支持到20位,请问有方法简单的支持上百个数据的序列化吗

### ISSUE THREAD

**Issue by tangjiands** [daixian/jsoncpp#1]

**Comment by daixian** [comment]
1. 目前支持32个成员字段，是由这个脚本自动写宏定义时候规定的，可以修改这个生成参数生成更大的JsonSerializableImpl.h文件。https://github.com/daixian/jsoncpp/blob/c3df44e7a132b21acf38e8e1da3848b5fb17573d/src/CodeCreate.py#L70
2. 也可以把DTO对象类型数据拆一下比如有C1有16个成员，C2有16个成员，把C1和C2都作为C3的成员，那么C3就有32个数据了。
